FROM nvidia/cuda:11.1.1-devel-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive

#### System package (uses default Python 3 version in Ubuntu 20.04)
RUN apt-get update -y && \
    apt-get install -y \
        git python3 python3-pip && \
    update-alternatives --install /usr/bin/python python /usr/bin/python3 1 && \
    update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1 && \
    pip install --upgrade pip

#### Python packages
RUN pip install torch==1.8.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html && pip cache purge
COPY requirements/requirements.txt .
RUN pip install -r requirements.txt && pip cache purge

### Fused kernels
RUN cd /tmp && git clone https://github.com/EleutherAI/gpt-neox.git && cd gpt-neox && git checkout e80d8caec7c778e0f014f506d0ea9ce0fc2f9d58 && python ./megatron/fused_kernels/setup.py install

WORKDIR /gpt-neox

CMD ./run.sh